http:
  port: 8080

# https:
#   port: 443
#   tls:
#     default:
#       key: "./certs/ss-key.pem"
#       cert: "./certs/ss-cert.pem"
#       ca: ["./certs/ss-csr.pem"]

apiEndpoints:
  sample:
    paths: '/api/v1/sample/*'

serviceEndpoints:
  sampleService:
    url: 'http://sample:3000'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - egateway-logger
  - oauth2
  - proxy
  - rate-limit

pipelines:
  - name: sample
    apiEndpoints:
      - sample
    policies:
      - egateway-logger:
      - proxy:
        - action:
            serviceEndpoint: sampleService
            changeOrigin: true
