http:
  port: 80

https:
  port: 443
  tls:
    default:
      key: "./config/certs/ss-key.pem"
      cert: "./config/certs/ss-cert.pem"
      ca: ["./config/certs/ss-csr.pem"]

apiEndpoints:
  # api:
  #   paths: '/ip'
  sample:
    paths: '/api/v1/sample/*'
  device:
    paths: '/api/v1/device/*'
  ticket:
    paths: '/api/v1/ticket/*'
  order:
    paths: '/api/v1/order/*'
  admin:
    paths: '/api/v1/admin/*'
  portal:
    paths: '/*'

serviceEndpoints:
  # httpbin:
  #   url: 'https://httpbin.org'
  sampleService:
    url: 'http://sample:3000'
  deviceService:
    url: 'http://device:3001'
  ticketService:
    url: 'http://device:3004'
  orderService:
    url: 'http://order:3002'
  adminService:
    url: 'http://admin:3003'
  portalService:
    url: 'http://portal:80'

policies:
  - basic-auth
  - cors
  - expression
  - egateway-logger
  - jwt
  - proxy
  - rate-limit

pipelines:
  # - default:
  #   apiEndpoints:
  #     - api
  #   policies:
  #     - egateway-logger:
  #     - jwt:
  #       - action:
  #           secretOrPublicKey: ${JWT_SECRET}
  #           checkCredentialExistence: false
  #     - proxy:
  #         - action:
  #             serviceEndpoint: httpbin 
  #             changeOrigin: true

  - name: sample
    apiEndpoints:
      - sample
    policies:
      - egateway-logger:
      - jwt:
        - action:
            secretOrPublicKey: ${JWT_SECRET}
            checkCredentialExistence: false
      - proxy:
        - action:
            serviceEndpoint: sampleService
            changeOrigin: true
  
  - name: device
    apiEndpoints:
      - device
    policies:
      - egateway-logger:
      - jwt:
        - action:
            secretOrPublicKey: ${JWT_SECRET}
            checkCredentialExistence: false
      - proxy:
        - action:
            serviceEndpoint: deviceService
            changeOrigin: true
  - name: ticket
      apiEndpoints:
        - ticket
      policies:
        - egateway-logger:
        - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false
        - proxy:
          - action:
              serviceEndpoint: ticketService
              changeOrigin: true
  - name: order
    apiEndpoints:
      - order
    policies:
      - egateway-logger:
      - jwt:
        - action:
            secretOrPublicKey: ${JWT_SECRET}
            checkCredentialExistence: false
      - proxy:
        - action:
            serviceEndpoint: orderService
            changeOrigin: true
    
  - name: admin
    apiEndpoints:
      - admin
    policies:
      - egateway-logger:
      - jwt:
        - action:
            secretOrPublicKey: ${JWT_SECRET}
            checkCredentialExistence: false
      - proxy:
        - action:
            serviceEndpoint: adminService
            changeOrigin: true
  
  - name: portal
    apiEndpoints:
      - portal
    policies:
      - proxy:
        - action:
            serviceEndpoint: portalService
            changeOrigin: true